Repository opea-project/GenAIExamples, pull requests merged in 2024-11, with the labels that each got.

#1071 MultimodalQnA Image and Audio Support Phase 1
  MultimodalQnA/README.md
  MultimodalQnA/docker_compose/intel/cpu/xeon/README.md
  MultimodalQnA/docker_compose/intel/cpu/xeon/compose.yaml
  MultimodalQnA/docker_compose/intel/cpu/xeon/set_env.sh
  MultimodalQnA/docker_compose/intel/hpu/gaudi/README.md
  MultimodalQnA/docker_compose/intel/hpu/gaudi/compose.yaml
  MultimodalQnA/docker_compose/intel/hpu/gaudi/set_env.sh
  MultimodalQnA/tests/test_compose_on_gaudi.sh
  MultimodalQnA/tests/test_compose_on_xeon.sh
  MultimodalQnA/ui/gradio/conversation.py
  MultimodalQnA/ui/gradio/multimodalqna_ui_gradio.py
  MultimodalQnA/ui/gradio/utils.py
  README.md
  docker_images_list.md
  supported_examples.md
Labels: r1.1

#1121 Fix left issue of tgi version update
  AvatarChatbot/docker_compose/intel/hpu/gaudi/compose.yaml
  AvatarChatbot/tests/test_compose_on_gaudi.sh
  ChatQnA/docker_compose/intel/cpu/xeon/README.md
Labels: WIP

#1134 Fix SearchQnA CI Issue
  SearchQnA/docker_compose/intel/hpu/gaudi/compose.yaml
  SearchQnA/tests/test_compose_on_gaudi.sh
  SearchQnA/ui/svelte/tests/searchQnA.spec.ts
Labels: r1.1

#1122 Add compose example for ChatQnA AMD ROCm deployment
  ChatQnA/docker_compose/amd/gpu/rocm/README.md
  ChatQnA/docker_compose/amd/gpu/rocm/compose.yaml
  ChatQnA/docker_compose/amd/gpu/rocm/set_env.sh
  ChatQnA/tests/test_compose_on_rocm.sh
Labels: feature

#1125 Add compose example for DocSum amd rocm deployment
  DocSum/docker_compose/amd/gpu/rocm/README.md
  DocSum/docker_compose/amd/gpu/rocm/compose.yaml
  DocSum/docker_compose/amd/gpu/rocm/set_env.sh
  DocSum/tests/test_compose_on_rocm.sh
Labels: feature

#1130 Adding files to deploy CodeGen application on AMD GPU
  CodeGen/docker_compose/amd/gpu/rocm/README.md
  CodeGen/docker_compose/amd/gpu/rocm/compose.yaml
  CodeGen/docker_compose/amd/gpu/rocm/set_env.sh
  CodeGen/tests/test_compose_on_rocm.sh
Labels: feature

#1138 Adding files to deploy CodeTrans application on AMD GPU
  CodeTrans/docker_compose/amd/gpu/rocm/README.md
  CodeTrans/docker_compose/amd/gpu/rocm/compose.yaml
  CodeTrans/docker_compose/amd/gpu/rocm/set_env.sh
  CodeTrans/tests/test_compose_on_rocm.sh
Labels: feature

#1154 Rename image name XXX-hpu to XXX-gaudi
  .github/workflows/_example-workflow.yml
  ChatQnA/docker_compose/intel/hpu/gaudi/compose_vllm.yaml
  ChatQnA/docker_image_build/build.yaml
  ChatQnA/kubernetes/intel/hpu/gaudi/manifest/chatqna-vllm.yaml
  ChatQnA/tests/test_compose_vllm_on_gaudi.sh
  docker_images_list.md
Labels: WIP
