Repository opea-project/GenAIExamples, pull requests merged in 2025-03, with the labels that each got.

#1622 Update compose.yaml for SearchQnA
  SearchQnA/docker_compose/amd/gpu/rocm/compose.yaml
  SearchQnA/docker_compose/intel/cpu/xeon/compose.yaml
  SearchQnA/docker_compose/intel/hpu/gaudi/compose.yaml
Labels: WIP

#1628 [ChatQnA] Show spinner after query to improve user experience (#1003)
  ChatQnA/ui/svelte/src/lib/shared/components/loading/Spinner.svelte
  ChatQnA/ui/svelte/src/routes/+page.svelte
Labels: OPEAHack

#1646 Add GitHub Action to check and close stale issues and PRs
  .github/workflows/daily_check_issue_and_pr.yml
Labels: WIP

#1623 [ChatQnA] Enable Prometheus and Grafana with telemetry docker compose file.
  ChatQnA/README.md
  ChatQnA/docker_compose/intel/cpu/xeon/README.md
  ChatQnA/docker_compose/intel/cpu/xeon/compose.telemetry.yaml
  ChatQnA/docker_compose/intel/cpu/xeon/compose_tgi.telemetry.yaml
  ChatQnA/docker_compose/intel/cpu/xeon/grafana/dashboards/download_opea_dashboard.sh
  ChatQnA/docker_compose/intel/cpu/xeon/grafana/provisioning/dashboards/local.yaml
  ChatQnA/docker_compose/intel/cpu/xeon/grafana/provisioning/datasources/datasource.yml
  ChatQnA/docker_compose/intel/cpu/xeon/prometheus.yaml
  ChatQnA/docker_compose/intel/cpu/xeon/set_env.sh
  ChatQnA/docker_compose/intel/hpu/gaudi/README.md
  ChatQnA/docker_compose/intel/hpu/gaudi/compose.telemetry.yaml
  ChatQnA/docker_compose/intel/hpu/gaudi/compose_tgi.telemetry.yaml
  ChatQnA/docker_compose/intel/hpu/gaudi/grafana/dashboards/download_opea_dashboard.sh
  ChatQnA/docker_compose/intel/hpu/gaudi/grafana/provisioning/dashboards/local.yaml
  ChatQnA/docker_compose/intel/hpu/gaudi/grafana/provisioning/datasources/datasource.yml
  ChatQnA/docker_compose/intel/hpu/gaudi/prometheus.yaml
  ChatQnA/docker_compose/intel/hpu/gaudi/set_env.sh
Labels: A1

#1669 Enable base image build in CI/CD
  .github/workflows/_build_comps_base_image.yml
  .github/workflows/manual-example-workflow.yml
  .github/workflows/nightly-docker-build-publish.yml
  .github/workflows/weekly-update-images.yml
  DocSum/Dockerfile
  DocSum/docker_image_build/build.yaml
  DocSum/tests/test_compose_on_gaudi.sh
  DocSum/tests/test_compose_on_rocm.sh
  DocSum/tests/test_compose_on_xeon.sh
Labels: WIP

#1700 [docs] Multimodal Endpoints Issue
  MultimodalQnA/README.md
  MultimodalQnA/docker_compose/amd/gpu/rocm/README.md
  MultimodalQnA/docker_compose/intel/cpu/xeon/README.md
  MultimodalQnA/docker_compose/intel/hpu/gaudi/README.md
Labels: A0
