Repository opea-project/GenAIExamples, pull requests merged in 2025-04, with the labels that each got.

#1637 Add short descriptions to the images OPEA publishes on Docker Hub
  .github/workflows/dockerhub-description.yml
  docker_images_list.md
Labels: OPEAHack

#1698 MultimodalQnA audio features completion
  MultimodalQnA/README.md
  MultimodalQnA/assets/img/audio-ingestion.png
  MultimodalQnA/assets/img/audio-query.png
  MultimodalQnA/assets/img/example_query.png
  MultimodalQnA/assets/img/image-ingestion.png
  MultimodalQnA/assets/img/image-query-text.png
  MultimodalQnA/assets/img/image-query-tts.png
  MultimodalQnA/assets/img/image-query.png
  MultimodalQnA/assets/img/ingest_pdf.png
  MultimodalQnA/assets/img/mmqna-ui.png
  MultimodalQnA/assets/img/pdf-ingestion.png
  MultimodalQnA/assets/img/pdf-query.png
  MultimodalQnA/assets/img/upload-gen-captions.png
  MultimodalQnA/assets/img/upload-gen-trans.png
  MultimodalQnA/assets/img/vector-store.png
  MultimodalQnA/assets/img/video-ingestion.png
  MultimodalQnA/assets/img/video-query.png
  MultimodalQnA/docker_compose/amd/gpu/rocm/compose.yaml
  MultimodalQnA/docker_compose/intel/cpu/xeon/README.md
  MultimodalQnA/docker_compose/intel/cpu/xeon/compose.yaml
  MultimodalQnA/docker_compose/intel/cpu/xeon/set_env.sh
  MultimodalQnA/docker_compose/intel/hpu/gaudi/README.md
  MultimodalQnA/docker_compose/intel/hpu/gaudi/compose.yaml
  MultimodalQnA/docker_compose/intel/hpu/gaudi/set_env.sh
  MultimodalQnA/docker_image_build/build.yaml
  MultimodalQnA/multimodalqna.py
  MultimodalQnA/tests/test_compose_on_gaudi.sh
  MultimodalQnA/tests/test_compose_on_rocm.sh
  MultimodalQnA/tests/test_compose_on_xeon.sh
  MultimodalQnA/ui/gradio/conversation.py
  MultimodalQnA/ui/gradio/multimodalqna_ui_gradio.py
  MultimodalQnA/ui/gradio/requirements.txt
  MultimodalQnA/ui/gradio/utils.py
Labels: v1.3

#1738 Add financial research agent.
  FinanceAgent/docker_compose/intel/hpu/gaudi/compose.yaml
  FinanceAgent/prompts/research_prompt.py
  FinanceAgent/tests/test_compose_on_gaudi.sh
  FinanceAgent/tools/research_agent_tools.yaml
  FinanceAgent/tools/research_tools.py
Labels: v1.3

#1757 CodGen Examples using-RAG-and-Agents
  CodeGen/README.md
  CodeGen/assets/img/codegen_gradio_ui_dataprep.png
  CodeGen/assets/img/codegen_gradio_ui_main.png
  CodeGen/assets/img/codegen_gradio_ui_query.png
  CodeGen/assets/img/codegen_gradio_ui_rm.png
  CodeGen/codegen.py
  CodeGen/docker_compose/intel/cpu/xeon/README.md
  CodeGen/docker_compose/intel/cpu/xeon/compose.yaml
  CodeGen/docker_compose/intel/hpu/gaudi/README.md
  CodeGen/docker_compose/intel/hpu/gaudi/compose.yaml
  CodeGen/docker_compose/set_env.sh
  CodeGen/docker_image_build/build.yaml
  CodeGen/tests/test_compose_on_gaudi.sh
  CodeGen/tests/test_compose_on_xeon.sh
  CodeGen/ui/docker/Dockerfile.gradio
  CodeGen/ui/gradio/README.md
  CodeGen/ui/gradio/codegen_ui_gradio.py
  CodeGen/ui/gradio/requirements.txt
Labels: feature, WIP

#1770 fix bugs in DocIndexRetriever
  DocIndexRetriever/README.md
  DocIndexRetriever/docker_compose/intel/cpu/xeon/README.md
  DocIndexRetriever/docker_compose/intel/cpu/xeon/compose.yaml
  DocIndexRetriever/docker_compose/intel/hpu/gaudi/README.md
  DocIndexRetriever/docker_compose/intel/hpu/gaudi/compose.yaml
  DocIndexRetriever/retrieval_tool.py
  DocIndexRetriever/tests/test.py
  DocIndexRetriever/tests/test_compose_milvus_on_gaudi.sh
  DocIndexRetriever/tests/test_compose_milvus_on_xeon.sh
  DocIndexRetriever/tests/test_compose_on_gaudi.sh
  DocIndexRetriever/tests/test_compose_on_xeon.sh
  DocIndexRetriever/tests/test_compose_without_rerank_on_xeon.sh
Labels: bug

#1618 Update model cache for MultimodalQnA
  MultimodalQnA/tests/test_compose_on_rocm.sh
Labels: WIP

#1743 Redefine docker images list.
  docker_images_list.md
Labels: WIP

#1790 update AgentQnA
  AgentQnA/README.md
  AgentQnA/docker_compose/intel/hpu/gaudi/compose.yaml
  AgentQnA/retrieval_tool/run_ingest_data.sh
  AgentQnA/tests/step4_launch_and_validate_agent_gaudi.sh
  AgentQnA/tests/test_compose_on_gaudi.sh
  AgentQnA/tools/worker_agent_tools.py
Labels: v1.3

#1696 Fix VideoQnA
  VideoQnA/docker_compose/intel/cpu/xeon/README.md
  VideoQnA/docker_compose/intel/cpu/xeon/compose.yaml
  VideoQnA/docker_compose/intel/cpu/xeon/set_env.sh
  VideoQnA/docker_image_build/build.yaml
  VideoQnA/tests/test_compose_on_xeon.sh
  VideoQnA/videoqna.py
Labels: bug, v1.3

#1822 Adding the two missing packages for ingest script
  AgentQnA/retrieval_tool/run_ingest_data.sh
Labels: v1.3

#1799 Enable health check for dataprep in ChatQnA
  ChatQnA/docker_compose/amd/gpu/rocm/compose.yaml
  ChatQnA/docker_compose/amd/gpu/rocm/compose_faqgen.yaml
  ChatQnA/docker_compose/amd/gpu/rocm/compose_faqgen_vllm.yaml
  ChatQnA/docker_compose/amd/gpu/rocm/compose_vllm.yaml
  ChatQnA/docker_compose/intel/cpu/aipc/compose.yaml
  ChatQnA/docker_compose/intel/cpu/xeon/compose.yaml
  ChatQnA/docker_compose/intel/cpu/xeon/compose_faqgen.yaml
  ChatQnA/docker_compose/intel/cpu/xeon/compose_faqgen_tgi.yaml
  ChatQnA/docker_compose/intel/cpu/xeon/compose_milvus.yaml
  ChatQnA/docker_compose/intel/cpu/xeon/compose_pinecone.yaml
  ChatQnA/docker_compose/intel/cpu/xeon/compose_qdrant.yaml
  ChatQnA/docker_compose/intel/cpu/xeon/compose_tgi.yaml
  ChatQnA/docker_compose/intel/cpu/xeon/compose_without_rerank.yaml
  ChatQnA/docker_compose/intel/hpu/gaudi/compose.yaml
  ChatQnA/docker_compose/intel/hpu/gaudi/compose_faqgen.yaml
  ChatQnA/docker_compose/intel/hpu/gaudi/compose_faqgen_tgi.yaml
  ChatQnA/docker_compose/intel/hpu/gaudi/compose_guardrails.yaml
  ChatQnA/docker_compose/intel/hpu/gaudi/compose_tgi.yaml
  ChatQnA/docker_compose/intel/hpu/gaudi/compose_without_rerank.yaml
  ChatQnA/docker_compose/nvidia/gpu/compose.yaml
Labels: bug, v1.3

#1755 new chatqna readme template
  ChatQnA/README.md
  ChatQnA/README_miscellaneous.md
  ChatQnA/docker_compose/intel/cpu/xeon/README.md
Labels: documentation, v1.3

#1842 Update README.md of ChatQnA for layout
  ChatQnA/README.md
  ChatQnA/README_miscellaneous.md
  ChatQnA/docker_compose/intel/cpu/xeon/README.md
Labels: documentation, v1.3

#1818 Remote inference support for examples in Productivity suite
  ChatQnA/chatqna.py
  ChatQnA/docker_compose/intel/cpu/xeon/compose_remote.yaml
  CodeGen/codegen.py
  CodeGen/docker_compose/intel/cpu/xeon/compose_remote.yaml
Labels: v1.3

#1850 Refine ChatQnA READMEs
  ChatQnA/README.md
  ChatQnA/README_miscellaneous.md
  ChatQnA/docker_compose/intel/cpu/xeon/README.md
  ChatQnA/docker_compose/intel/cpu/xeon/README_faqgen.md
  ChatQnA/docker_compose/intel/cpu/xeon/README_pinecone.md
  ChatQnA/docker_compose/intel/cpu/xeon/README_qdrant.md
  ChatQnA/docker_compose/intel/hpu/gaudi/README.md
Labels: documentation, v1.3

#1794 Refine readme of InstructionTuning
  InstructionTuning/README.md
  InstructionTuning/docker_compose/intel/cpu/xeon/README.md
  InstructionTuning/docker_compose/intel/hpu/gaudi/README.md
Labels: documentation, v1.3

#1795 [ Translation ] Refine documents
  Translation/README.md
  Translation/docker_compose/amd/gpu/rocm/README.md
  Translation/docker_compose/intel/cpu/xeon/README.md
  Translation/docker_compose/intel/hpu/gaudi/README.md
Labels: documentation, v1.3

#1802 Refine documents for DocSum
  DocSum/README.md
  DocSum/README_miscellaneous.md
  DocSum/docker_compose/amd/gpu/rocm/README.md
  DocSum/docker_compose/intel/cpu/xeon/README.md
  DocSum/docker_compose/intel/hpu/gaudi/README.md
  DocSum/docker_compose/set_env.sh
Labels: documentation, v1.3

#1833 add AudioQnA key parameters to comply with the image size reduction
  AudioQnA/docker_compose/intel/cpu/xeon/compose_multilang.yaml
Labels: bug, v1.3

#1844 Update chatqna values file changes
  ChatQnA/kubernetes/helm/cpu-milvus-values.yaml
  ChatQnA/kubernetes/helm/cpu-values.yaml
  ChatQnA/kubernetes/helm/guardrails-gaudi-values.yaml
Labels: v1.3

#1639 [Bug: 900] Create a version of MultimodalQnA example with Zilliz/Milvus as Vector DB
  MultimodalQnA/docker_compose/intel/cpu/xeon/README.md
  MultimodalQnA/docker_compose/intel/cpu/xeon/compose_milvus.yaml
  MultimodalQnA/docker_compose/intel/cpu/xeon/config/milvus.yaml
  MultimodalQnA/docker_compose/intel/hpu/gaudi/README.md
  MultimodalQnA/docker_compose/intel/hpu/gaudi/compose_milvus.yaml
  MultimodalQnA/docker_compose/intel/hpu/gaudi/config/milvus.yaml
  MultimodalQnA/tests/test_compose_milvus_on_xeon.sh
Labels: OPEAHack, v1.3

#1840 Added Initial version of DocSum support for benchmarking scripts for OPEA
  DocSum/benchmark_docsum.yaml
  benchmark.py
  deploy.py
Labels: feature, v1.3

#1849 hot fix for permission issue
  EdgeCraftRAG/Dockerfile.server
Labels: v1.3

#1796 Refine the READMEs of CodeTrans
  CodeTrans/README.md
  CodeTrans/README_miscellaneous.md
  CodeTrans/docker_compose/amd/gpu/rocm/README.md
  CodeTrans/docker_compose/intel/cpu/xeon/README.md
  CodeTrans/docker_compose/intel/hpu/gaudi/README.md
Labels: documentation, v1.3

#1803 [ SearchQnA ] Refine documents
  SearchQnA/README.md
  SearchQnA/README_miscellaneous.md
  SearchQnA/docker_compose/amd/gpu/rocm/README.md
  SearchQnA/docker_compose/intel/cpu/xeon/README.md
  SearchQnA/docker_compose/intel/hpu/gaudi/README.md
Labels: documentation, v1.3

#1804 Refine readme of AudioQnA
  AudioQnA/README.md
  AudioQnA/README_miscellaneous.md
  AudioQnA/docker_compose/intel/cpu/xeon/README.md
  AudioQnA/docker_compose/intel/hpu/gaudi/README.md
Labels: documentation, v1.3

#1797 Refine readme of CodeGen
  CodeGen/README.md
  CodeGen/benchmark/accuracy/README.md
  CodeGen/benchmark/performance/README.md
  CodeGen/docker_compose/amd/gpu/rocm/README.md
  CodeGen/docker_compose/intel/cpu/xeon/README.md
  CodeGen/docker_compose/intel/hpu/gaudi/README.md
  CodeGen/kubernetes/gmc/README.md
  CodeGen/kubernetes/helm/README.md
Labels: documentation, v1.3

#1859 Fixes for MultimodalQnA with the Milvus vector db
  MultimodalQnA/docker_compose/intel/cpu/xeon/README.md
  MultimodalQnA/docker_compose/intel/cpu/xeon/compose_milvus.yaml
Labels: v1.3

#1862 Refine AuidoQnA README.MD for AMD ROCm docker compose deployment
  AudioQnA/docker_compose/amd/gpu/rocm/README.md
  CodeGen/docker_compose/amd/gpu/rocm/README.md
Labels: documentation, v1.3

#1874 Remove proxy in CodeTrans test
  ChatQnA/tests/test_compose_milvus_on_xeon.sh
  CodeTrans/tests/test_compose_on_gaudi.sh
  CodeTrans/tests/test_compose_on_rocm.sh
  CodeTrans/tests/test_compose_on_xeon.sh
  CodeTrans/tests/test_compose_tgi_on_gaudi.sh
  CodeTrans/tests/test_compose_tgi_on_xeon.sh
  CodeTrans/tests/test_compose_vllm_on_rocm.sh
Labels: bug, v1.3

#1875 CodeTrans - refactoring README.md for deploy application on ROCm with Docker Compose
  CodeTrans/docker_compose/amd/gpu/rocm/README.md
Labels: documentation, v1.3

#1857 ChatQnA - refactoring README.md for deploy application on ROCm
  ChatQnA/docker_compose/amd/gpu/rocm/README.md
  ChatQnA/docker_compose/amd/gpu/rocm/compose.yaml
  ChatQnA/docker_compose/amd/gpu/rocm/compose_faqgen.yaml
  ChatQnA/docker_compose/amd/gpu/rocm/compose_faqgen_vllm.yaml
Labels: documentation, v1.3

#1876 Refine README.MD for SearchQnA on AMD ROCm platform
  SearchQnA/docker_compose/amd/gpu/rocm/README.md
Labels: documentation, v1.3

#1881 DocSum - refactoring README.md for deploy application on ROCm
  DocSum/docker_compose/amd/gpu/rocm/README.md
Labels: documentation, v1.3

#1882 README fixes Finance Example
  FinanceAgent/README.md
Labels: documentation, v1.3

#1883 Update benchmark scripts
  ChatQnA/benchmark_chatqna.yaml
  DocSum/benchmark_docsum.yaml
  README-deploy-benchmark.md
  deploy.py
  deploy_and_benchmark.py
  requirements.txt
Labels: v1.3
